// ============================================================
// CHARACTER CLASS DEFINITIONS
// Extracted from items.js. Contains all class configs including
// base stats, skills, talent trees, and allowed items.
// ============================================================

// ========== CHARACTER CLASSES ==========
const CLASSES = {
    knight: {
        name: 'Rycerz',
        icon: '⚔️',
        desc: 'Silny w obronie i ataku z bliska.',
        color: '#e74c3c',
        baseStats: { hp: 150, mp: 30, damage: 8, armor: 5, accuracy: 10, dodge: 2 },
        baseAttributes: { str: 3, dex: 1, agi: 1, vit: 3, int: 0 },
        hpPerLevel: 12, mpPerLevel: 3,
        attacksPerTurn: 1,
        baseAttackSpeed: 1.5,
        allowedItems: ['sword','longsword','axe','battleaxe','mace','warhammer','helmet','great_helm','armor','plate_armor','pants','plate_legs','boots','plate_boots','shield','tower_shield'],
        skills: [
            { level: 1,  id: 'shield_bash', name: 'Uderzenie Tarczą', desc: 'Ogłusza wroga. Obrażenia 1.2x (+0.2x/lv)', cost: 8, type: 'melee', baseMult: 1.2, multPerLv: 0.2 },
            { level: 2,  id: 'power_strike', name: 'Potężne Uderzenie', desc: 'Obrażenia 2x ATK (+0.3x/lv)', cost: 12, type: 'melee', baseMult: 2.0, multPerLv: 0.3 },
            { level: 4,  id: 'iron_skin', name: 'Żelazna Skóra', desc: '+50% DEF na 3 tury (+1 tura/lv)', cost: 15, type: 'buff' },
            { level: 6,  id: 'whirlwind', name: 'Wir Ostrza', desc: 'Uderza wszystkich dookoła 1.5x (+0.2x/lv)', cost: 20, type: 'aoe', baseMult: 1.5, multPerLv: 0.2 },
            { level: 8,  id: 'taunt', name: 'Prowokacja', desc: 'Wszystkie potwory atakują ciebie (+1 tura/lv)', cost: 10, type: 'aoe' },
            { level: 10, id: 'execute', name: 'Egzekucja', desc: '3x dmg jeśli wróg <30% HP (+0.5x/lv)', cost: 25, type: 'melee', baseMult: 3.0, multPerLv: 0.5 },
            { level: 13, id: 'war_cry', name: 'Okrzyk Wojenny', desc: '+30% ATK na 3 tury (+5%/lv)', cost: 18, type: 'buff' },
            { level: 16, id: 'shield_wall', name: 'Mur Tarcz', desc: 'Blokuje 80% dmg przez 2 tury (+1/lv)', cost: 22, type: 'buff' },
            { level: 19, id: 'ground_slam', name: 'Trzęsienie', desc: 'Ogłusza i zadaje 2x w promieniu 2 (+0.3x/lv)', cost: 30, type: 'aoe', baseMult: 2.0, multPerLv: 0.3 },
            { level: 22, id: 'last_stand', name: 'Ostatnia Szansa', desc: 'Nie możesz zginąć przez 3 tury (+1/lv)', cost: 35, type: 'buff' },
            { level: 28, id: 'cleave', name: 'Rozcięcie', desc: '2.5x ATK w łuku przed sobą (+0.3x/lv)', cost: 24, type: 'aoe', baseMult: 2.5, multPerLv: 0.3 },
            { level: 35, id: 'blood_rage', name: 'Krwawa Furia', desc: '+40% ATK, -20% DEF na 5s (+5% ATK/lv)', cost: 28, type: 'buff' },
            { level: 42, id: 'impale', name: 'Nadzianie', desc: '4x ATK + krwawienie 5s (+0.6x/lv)', cost: 32, type: 'melee', baseMult: 4.0, multPerLv: 0.6 },
            { level: 50, id: 'avalanche', name: 'Lawina', desc: '3x AoE promień 3, ogłuszenie (+0.4x/lv)', cost: 40, type: 'aoe', baseMult: 3.0, multPerLv: 0.4 },
            { level: 60, id: 'titan_form', name: 'Forma Tytana', desc: '+100% HP, +50% ATK na 8s (+1s/lv)', cost: 50, type: 'buff' },
        ],
        tree: {
            defense: { name: 'Obrona', nodes: [
                { id: 'thick_skin', name: 'Gruba Skóra', desc: '+3 Pancerz', stat: 'armor', val: 3 },
                { id: 'vitality', name: 'Witalność', desc: '+15 HP', stat: 'maxHp', val: 15 },
                { id: 'block', name: 'Blok', desc: '+5 Pancerz', stat: 'armor', val: 5 },
                { id: 'fortify', name: 'Fortyfikacja', desc: '+25 HP', stat: 'maxHp', val: 25 },
                { id: 'unbreakable', name: 'Niezłomny', desc: '+8 Pancerz', stat: 'armor', val: 8 },
                { id: 'iron_fortress', name: 'Żelazna Twierdza', desc: '+12 Pancerz', stat: 'armor', val: 12 },
                { id: 'bulwark', name: 'Bastion', desc: '+40 HP', stat: 'maxHp', val: 40 },
                { id: 'titan_armor', name: 'Zbroja Tytana', desc: '+15 Pancerz', stat: 'armor', val: 15 },
            ]},
            offense: { name: 'Atak', nodes: [
                { id: 'sharp_edge', name: 'Ostre Ostrze', desc: '+3 Obrażenia', stat: 'damage', val: 3 },
                { id: 'brutal', name: 'Brutalność', desc: '+5 Obrażenia', stat: 'damage', val: 5 },
                { id: 'rage', name: 'Furia', desc: '+8 Obrażenia', stat: 'damage', val: 8 },
                { id: 'berserk', name: 'Berserk', desc: '+12 Obrażenia', stat: 'damage', val: 12 },
                { id: 'warlord', name: 'Pan Wojny', desc: '+15 Obrażenia', stat: 'damage', val: 15 },
                { id: 'crusher', name: 'Miażdżyciel', desc: '+18 Obrażenia', stat: 'damage', val: 18 },
                { id: 'conqueror', name: 'Zdobywca', desc: '+22 Obrażenia', stat: 'damage', val: 22 },
                { id: 'god_of_war', name: 'Bóg Wojny', desc: '+30 Obrażenia', stat: 'damage', val: 30 },
            ]},
            mastery: { name: 'Mistrzostwo', nodes: [
                { id: 'crit_strike', name: 'Celny Cios', desc: '+3 Kryty', stat: 'critChance', val: 3 },
                { id: 'stun_mastery', name: 'Ogłuszanie', desc: '+2 Ogłuszenie', stat: 'stunChance', val: 2 },
                { id: 'riposte', name: 'Riposta', desc: '+5 Celność', stat: 'accuracy', val: 5 },
                { id: 'battle_focus', name: 'Skupienie', desc: '+5 Kryty', stat: 'critChance', val: 5 },
                { id: 'executioner', name: 'Egzekutor', desc: '+3 Ogłuszenie', stat: 'stunChance', val: 3 },
            ]},
        },
    },
    rogue: {
        name: 'Łotrzyk',
        icon: '🗡️',
        desc: 'Zwinny, 2 ataki na turę, niewidzialność.',
        color: '#2ecc71',
        baseStats: { hp: 100, mp: 50, damage: 6, armor: 2, accuracy: 12, dodge: 8 },
        baseAttributes: { str: 1, dex: 3, agi: 3, vit: 1, int: 0 },
        hpPerLevel: 8, mpPerLevel: 4,
        attacksPerTurn: 2,
        baseAttackSpeed: 1.0,
        allowedItems: ['dagger','kris','rapier','sword','hood','mask','cape','shadow_vest','leather_armor','leggings','shadow_legs','boots','swift_boots','offhand_dagger','buckler'],
        skills: [
            { level: 1,  id: 'stealth', name: 'Niewidzialność', desc: 'Niewidzialny na 5 kratek (+2/lv)', cost: 10, type: 'buff' },
            { level: 2,  id: 'backstab', name: 'Cios w Plecy', desc: '2x obrażenia (+0.3x/lv)', cost: 12, type: 'melee', baseMult: 2.0, multPerLv: 0.3 },
            { level: 4,  id: 'poison_blade', name: 'Zatrute Ostrze', desc: 'Obrażenia + trucizna 3 tury (+1/lv)', cost: 15, type: 'melee', baseMult: 1.5, multPerLv: 0.2 },
            { level: 6,  id: 'shadow_step', name: 'Krok Cienia', desc: 'Teleport za wroga + 2x atak (+0.3x/lv)', cost: 18, type: 'melee', baseMult: 2.0, multPerLv: 0.3 },
            { level: 8,  id: 'smoke_bomb', name: 'Bomba Dymna', desc: 'Ogłusza wrogów dookoła na 2 tury (+1/lv)', cost: 14, type: 'aoe' },
            { level: 10, id: 'assassinate', name: 'Zamach', desc: '4x dmg jeśli niewidzialny (+0.5x/lv)', cost: 25, type: 'melee', baseMult: 4.0, multPerLv: 0.5 },
            { level: 13, id: 'blade_fury', name: 'Furia Ostrzy', desc: 'Atak 3x na losowych wrogów (+1 atak/lv)', cost: 20, type: 'aoe', baseMult: 1.0, multPerLv: 0.15 },
            { level: 16, id: 'mark_death', name: 'Znak Śmierci', desc: 'Oznaczony wróg dostaje +50% dmg (+10%/lv)', cost: 16, type: 'melee' },
            { level: 19, id: 'vanish', name: 'Zniknięcie', desc: 'Natychmiastowa niewidzialność + leczenie 20% HP (+5%/lv)', cost: 22, type: 'buff' },
            { level: 22, id: 'death_blossom', name: 'Kwiat Śmierci', desc: 'Masowy atak 3x na wszystkich (+0.4x/lv)', cost: 35, type: 'aoe', baseMult: 3.0, multPerLv: 0.4 },
            { level: 28, id: 'envenom', name: 'Zatruwanie', desc: 'Trucizna na 6s, -30% DEF wroga (+1s/lv)', cost: 20, type: 'melee', baseMult: 1.0, multPerLv: 0.15 },
            { level: 35, id: 'shadow_dance', name: 'Taniec Cieni', desc: '+60% Unik i +40% ATK na 5s (+1s/lv)', cost: 30, type: 'buff' },
            { level: 42, id: 'kidney_shot', name: 'Cios Nerkowy', desc: '3.5x ATK + ogłuszenie 3s (+0.5x/lv)', cost: 28, type: 'melee', baseMult: 3.5, multPerLv: 0.5 },
            { level: 50, id: 'shadow_army', name: 'Armia Cieni', desc: 'Tworzy 3 klony atakujące po 1x (+0.2x/lv)', cost: 45, type: 'aoe', baseMult: 1.0, multPerLv: 0.2 },
            { level: 60, id: 'reaper', name: 'Żniwiarz', desc: '6x ATK z ukrycia, reset stealth (+1x/lv)', cost: 55, type: 'melee', baseMult: 6.0, multPerLv: 1.0 },
        ],
        tree: {
            agility: { name: 'Zwinność', nodes: [
                { id: 'quick_feet', name: 'Szybkie Nogi', desc: '+2 Unik', stat: 'dodge', val: 2 },
                { id: 'evasion', name: 'Uniki', desc: '+3 Unik', stat: 'dodge', val: 3 },
                { id: 'swift', name: 'Błyskawica', desc: '+5 Unik', stat: 'dodge', val: 5 },
                { id: 'ghost', name: 'Duch', desc: '+8 Unik', stat: 'dodge', val: 8 },
                { id: 'phantom', name: 'Fantom', desc: '+10 Unik', stat: 'dodge', val: 10 },
                { id: 'wind_walker', name: 'Chodzący po Wietrze', desc: '+12 Unik', stat: 'dodge', val: 12 },
                { id: 'untouchable', name: 'Nieuchwytny', desc: '+15 Unik', stat: 'dodge', val: 15 },
                { id: 'shadow_lord', name: 'Władca Cieni', desc: '+20 Unik', stat: 'dodge', val: 20 },
            ]},
            lethality: { name: 'Morderczość', nodes: [
                { id: 'keen_edge', name: 'Celny Cios', desc: '+3 Obrażenia', stat: 'damage', val: 3 },
                { id: 'exploit', name: 'Eksploatacja', desc: '+5 Obrażenia', stat: 'damage', val: 5 },
                { id: 'critical', name: 'Krytyczny', desc: '+8 Obrażenia', stat: 'damage', val: 8 },
                { id: 'deadly', name: 'Śmiercionośny', desc: '+10 Obrażenia', stat: 'damage', val: 10 },
                { id: 'master', name: 'Mistrz Cieni', desc: '+15 Obrażenia', stat: 'damage', val: 15 },
                { id: 'assassin', name: 'Zabójca', desc: '+18 Obrażenia', stat: 'damage', val: 18 },
                { id: 'death_dealer', name: 'Siewca Śmierci', desc: '+22 Obrażenia', stat: 'damage', val: 22 },
                { id: 'reaper_blade', name: 'Ostrze Żniwiarza', desc: '+30 Obrażenia', stat: 'damage', val: 30 },
            ]},
            poison: { name: 'Trucizny', nodes: [
                { id: 'venom_coat', name: 'Jadowita Powłoka', desc: '+2 Kryty', stat: 'critChance', val: 2 },
                { id: 'toxic_blade', name: 'Toksyczne Ostrze', desc: '+3 Kryty', stat: 'critChance', val: 3 },
                { id: 'paralytic', name: 'Paraliżujący', desc: '+5 Kryty', stat: 'critChance', val: 5 },
                { id: 'master_poison', name: 'Mistrz Trucizn', desc: '+4 Mnożnik Kryty', stat: 'critMult', val: 4 },
                { id: 'death_touch', name: 'Dotyk Śmierci', desc: '+8 Kryty', stat: 'critChance', val: 8 },
            ]},
        },
    },
    mage: {
        name: 'Mag',
        icon: '🪄',
        desc: 'Ataki dystansowe (3 kratki), kula ognia.',
        color: '#3498db',
        baseStats: { hp: 80, mp: 120, damage: 5, armor: 1, accuracy: 8, dodge: 3 },
        baseAttributes: { str: 0, dex: 1, agi: 1, vit: 1, int: 5 },
        hpPerLevel: 6, mpPerLevel: 8,
        attacksPerTurn: 1,
        baseAttackSpeed: 2.0,
        attackRange: 3,
        allowedItems: ['wand','staff','scepter','hat','circlet','robe','arcane_robe','pants','shoes','arcane_boots','tome','orb'],
        skills: [
            { level: 1,  id: 'fireball', name: 'Kula Ognia', desc: 'Obszarowe 1.5x w promieniu 1 (+0.2x/lv)', cost: 12, type: 'ranged_aoe', baseMult: 1.5, multPerLv: 0.2 },
            { level: 2,  id: 'ice_bolt', name: 'Lodowy Pocisk', desc: '2x ATK + zamrożenie (+0.3x/lv)', cost: 10, type: 'ranged', baseMult: 2.0, multPerLv: 0.3 },
            { level: 4,  id: 'mana_shield', name: 'Tarcza Many', desc: 'Absorbuje dmg za MP przez 3 tury (+1/lv)', cost: 20, type: 'buff' },
            { level: 6,  id: 'lightning', name: 'Błyskawica', desc: '2.5x ATK natychmiastowe (+0.4x/lv)', cost: 18, type: 'ranged', baseMult: 2.5, multPerLv: 0.4 },
            { level: 8,  id: 'arcane_blast', name: 'Fala Arkany', desc: 'Odpycha i zadaje 1.5x (+0.2x/lv)', cost: 14, type: 'aoe', baseMult: 1.5, multPerLv: 0.2 },
            { level: 10, id: 'frost_nova', name: 'Mroźna Nova', desc: 'Zamraża wszystkich na 2 tury (+1/lv)', cost: 22, type: 'aoe' },
            { level: 13, id: 'chain_lightning', name: 'Łańcuch Błyskawic', desc: 'Uderza 3 wrogów po kolei 2x (+0.3x/lv)', cost: 24, type: 'ranged', baseMult: 2.0, multPerLv: 0.3 },
            { level: 16, id: 'teleport', name: 'Teleportacja', desc: 'Teleportuj się 5 kratek (+1/lv) w kierunku', cost: 15, type: 'buff' },
            { level: 19, id: 'meteor', name: 'Meteor', desc: '4x ATK obszarowe w promieniu 2 (+0.5x/lv)', cost: 35, type: 'ranged_aoe', baseMult: 4.0, multPerLv: 0.5 },
            { level: 22, id: 'time_stop', name: 'Zatrzymanie Czasu', desc: 'Zamraża WSZYSTKO na 3 tury (+1/lv)', cost: 40, type: 'aoe' },
            { level: 28, id: 'blizzard', name: 'Zamieć', desc: '2x AoE w promieniu 3, spowolnienie (+0.3x/lv)', cost: 30, type: 'ranged_aoe', baseMult: 2.0, multPerLv: 0.3 },
            { level: 35, id: 'arcane_barrier', name: 'Bariera Arkany', desc: 'Tarcza absorbująca 50% HP, odbija 20% dmg (+5%/lv)', cost: 35, type: 'buff' },
            { level: 42, id: 'inferno', name: 'Inferno', desc: '3x AoE + podpalenie na 5s w promieniu 2 (+0.4x/lv)', cost: 38, type: 'ranged_aoe', baseMult: 3.0, multPerLv: 0.4 },
            { level: 50, id: 'cataclysm', name: 'Kataklizm', desc: '5x AoE w promieniu 4 (+0.6x/lv)', cost: 50, type: 'ranged_aoe', baseMult: 5.0, multPerLv: 0.6 },
            { level: 60, id: 'arcane_ascension', name: 'Arcymagiczne Wniebowzięcie', desc: '+80% DMG, -50% koszty MP na 10s', cost: 60, type: 'buff' },
        ],
        tree: {
            power: { name: 'Moc', nodes: [
                { id: 'arcane_power', name: 'Moc Arkany', desc: '+4 Obrażenia', stat: 'damage', val: 4 },
                { id: 'empower', name: 'Wzmocnienie', desc: '+6 Obrażenia', stat: 'damage', val: 6 },
                { id: 'surge', name: 'Fala Mocy', desc: '+10 Obrażenia', stat: 'damage', val: 10 },
                { id: 'overcharge', name: 'Przeciążenie', desc: '+14 Obrażenia', stat: 'damage', val: 14 },
                { id: 'archmage', name: 'Arcymag', desc: '+20 Obrażenia', stat: 'damage', val: 20 },
                { id: 'grand_sorcerer', name: 'Wielki Czarodziej', desc: '+25 Obrażenia', stat: 'damage', val: 25 },
                { id: 'elemental_lord', name: 'Władca Żywiołów', desc: '+30 Obrażenia', stat: 'damage', val: 30 },
                { id: 'supreme_mage', name: 'Najwyższy Mag', desc: '+40 Obrażenia', stat: 'damage', val: 40 },
            ]},
            wisdom: { name: 'Mądrość', nodes: [
                { id: 'meditation', name: 'Medytacja', desc: '+15 MP', stat: 'maxMp', val: 15 },
                { id: 'insight', name: 'Wgląd', desc: '+20 MP', stat: 'maxMp', val: 20 },
                { id: 'clarity', name: 'Jasność', desc: '+30 MP', stat: 'maxMp', val: 30 },
                { id: 'enlighten', name: 'Oświecenie', desc: '+40 MP', stat: 'maxMp', val: 40 },
                { id: 'transcend', name: 'Transcendencja', desc: '+60 MP', stat: 'maxMp', val: 60 },
                { id: 'infinite_mind', name: 'Nieskończony Umysł', desc: '+80 MP', stat: 'maxMp', val: 80 },
                { id: 'mana_well', name: 'Studnia Many', desc: '+100 MP', stat: 'maxMp', val: 100 },
                { id: 'cosmic_mind', name: 'Kosmiczny Umysł', desc: '+150 MP', stat: 'maxMp', val: 150 },
            ]},
            cdr_mastery: { name: 'Redukcja CD', nodes: [
                { id: 'quick_cast', name: 'Szybkie Zaklęcie', desc: '+2 CDR', stat: 'cdr', val: 2 },
                { id: 'flow', name: 'Przepływ', desc: '+3 CDR', stat: 'cdr', val: 3 },
                { id: 'haste', name: 'Pośpiech', desc: '+4 CDR', stat: 'cdr', val: 4 },
                { id: 'time_warp', name: 'Zakrzywienie Czasu', desc: '+5 CDR', stat: 'cdr', val: 5 },
                { id: 'chrono_master', name: 'Mistrz Czasu', desc: '+8 CDR', stat: 'cdr', val: 8 },
            ]},
        },
    },
    archer: {
        name: 'Łucznik',
        icon: '🏹',
        desc: 'Ataki dystansowe (4 kratki), włócznie, łuki.',
        color: '#e67e22',
        baseStats: { hp: 110, mp: 50, damage: 6, armor: 3, accuracy: 14, dodge: 5 },
        baseAttributes: { str: 2, dex: 3, agi: 2, vit: 1, int: 0 },
        hpPerLevel: 8, mpPerLevel: 4,
        attacksPerTurn: 1,
        baseAttackSpeed: 1.3,
        attackRange: 4,
        allowedItems: ['bow','longbow','crossbow','heavy_crossbow','spear','javelin','hood','ranger_hat','leather_armor','ranger_vest','leggings','ranger_legs','boots','swift_boots','quiver','enchanted_quiver'],
        skills: [
            { level: 1,  id: 'aimed_shot', name: 'Celny Strzał', desc: '2x ATK dystansowy (+0.3x/lv)', cost: 10, type: 'ranged', baseMult: 2.0, multPerLv: 0.3 },
            { level: 2,  id: 'multi_shot', name: 'Wielostrzał', desc: 'Strzela w 3 wrogów 1x (+0.15x/lv)', cost: 14, type: 'ranged_aoe', baseMult: 1.0, multPerLv: 0.15 },
            { level: 4,  id: 'dodge_roll', name: 'Unik', desc: '+30% AGI na 5s (+1s/lv)', cost: 12, type: 'buff' },
            { level: 6,  id: 'piercing_arrow', name: 'Przebijający Strzał', desc: '2.5x ATK ignoruje DEF (+0.4x/lv)', cost: 18, type: 'ranged', baseMult: 2.5, multPerLv: 0.4 },
            { level: 8,  id: 'rain_arrows', name: 'Deszcz Strzał', desc: 'Obszarowe 1.5x w promieniu 2 (+0.2x/lv)', cost: 22, type: 'ranged_aoe', baseMult: 1.5, multPerLv: 0.2 },
            { level: 10, id: 'spear_throw', name: 'Rzut Włócznią', desc: '3x ATK + ogłuszenie, włócznia ląduje na ziemi (+0.5x/lv)', cost: 20, type: 'ranged', baseMult: 3.0, multPerLv: 0.5, dropsSpear: true },
            { level: 13, id: 'hawk_eye', name: 'Sokolie Oko', desc: '+50% crit na 6s (+1s/lv)', cost: 16, type: 'buff' },
            { level: 16, id: 'trap', name: 'Pułapka', desc: 'Ogłusza wrogów w promieniu 1 na 3s (+1s/lv)', cost: 18, type: 'aoe' },
            { level: 19, id: 'sniper_shot', name: 'Snajperski Strzał', desc: '5x ATK na 1 cel (+0.8x/lv)', cost: 30, type: 'ranged', baseMult: 5.0, multPerLv: 0.8 },
            { level: 22, id: 'arrow_storm', name: 'Burza Strzał', desc: 'Masowy 3x na wszystkich w zasięgu (+0.4x/lv)', cost: 40, type: 'ranged_aoe', baseMult: 3.0, multPerLv: 0.4 },
            { level: 28, id: 'explosive_arrow', name: 'Eksplozyjny Strzał', desc: '2x AoE promień 2 + podpalenie (+0.3x/lv)', cost: 26, type: 'ranged_aoe', baseMult: 2.0, multPerLv: 0.3 },
            { level: 35, id: 'camouflage', name: 'Kamuflaż', desc: 'Niewidzialność + +50% crit na 5s (+1s/lv)', cost: 24, type: 'buff' },
            { level: 42, id: 'javelin_barrage', name: 'Salwa Włóczni', desc: 'Rzuca 5 włóczni po 2x ATK (+0.3x/lv)', cost: 35, type: 'ranged_aoe', baseMult: 2.0, multPerLv: 0.3, dropsSpear: true },
            { level: 50, id: 'phantom_arrows', name: 'Widmowe Strzały', desc: '4x na wszystkich, ignoruje DEF (+0.5x/lv)', cost: 45, type: 'ranged_aoe', baseMult: 4.0, multPerLv: 0.5 },
            { level: 60, id: 'wrath_of_sky', name: 'Gniew Niebios', desc: '6x AoE promień 4, ogłuszenie 3s (+0.8x/lv)', cost: 55, type: 'ranged_aoe', baseMult: 6.0, multPerLv: 0.8 },
        ],
        tree: {
            precision: { name: 'Precyzja', nodes: [
                { id: 'steady_aim', name: 'Pewna Ręka', desc: '+3 Obrażenia', stat: 'damage', val: 3 },
                { id: 'focus', name: 'Skupienie', desc: '+5 Obrażenia', stat: 'damage', val: 5 },
                { id: 'marksman', name: 'Strzelec', desc: '+8 Obrażenia', stat: 'damage', val: 8 },
                { id: 'sharpshooter', name: 'Snajper', desc: '+12 Obrażenia', stat: 'damage', val: 12 },
                { id: 'deadeye', name: 'Śmiertelne Oko', desc: '+15 Obrażenia', stat: 'damage', val: 15 },
                { id: 'eagle_eye', name: 'Orlim Okiem', desc: '+20 Obrażenia', stat: 'damage', val: 20 },
                { id: 'wind_archer', name: 'Łucznik Wiatru', desc: '+25 Obrażenia', stat: 'damage', val: 25 },
                { id: 'divine_archer', name: 'Boski Łucznik', desc: '+35 Obrażenia', stat: 'damage', val: 35 },
            ]},
            survival: { name: 'Przetrwanie', nodes: [
                { id: 'tough_skin', name: 'Twarda Skóra', desc: '+10 HP', stat: 'maxHp', val: 10 },
                { id: 'nimble', name: 'Zwinność', desc: '+3 Unik', stat: 'dodge', val: 3 },
                { id: 'hardened', name: 'Zahartowany', desc: '+20 HP', stat: 'maxHp', val: 20 },
                { id: 'wind_runner', name: 'Biegacz', desc: '+5 Unik', stat: 'dodge', val: 5 },
                { id: 'ranger', name: 'Strażnik', desc: '+30 HP', stat: 'maxHp', val: 30 },
                { id: 'forest_guardian', name: 'Strażnik Lasu', desc: '+8 Unik', stat: 'dodge', val: 8 },
                { id: 'survivor', name: 'Ocalały', desc: '+40 HP', stat: 'maxHp', val: 40 },
                { id: 'nature_bond', name: 'Więź Natury', desc: '+60 HP', stat: 'maxHp', val: 60 },
            ]},
            accuracy_tree: { name: 'Celność', nodes: [
                { id: 'true_aim', name: 'Pewny Cel', desc: '+3 Celność', stat: 'accuracy', val: 3 },
                { id: 'keen_sight', name: 'Bystry Wzrok', desc: '+5 Celność', stat: 'accuracy', val: 5 },
                { id: 'sniper_training', name: 'Trening Snajperski', desc: '+3 Kryty', stat: 'critChance', val: 3 },
                { id: 'eagle_precision', name: 'Precyzja Orła', desc: '+8 Celność', stat: 'accuracy', val: 8 },
                { id: 'perfect_aim', name: 'Doskonały Cel', desc: '+5 Kryty', stat: 'critChance', val: 5 },
            ]},
        },
    },
    novice: {
        name: 'Nowicjusz',
        icon: '🌱',
        desc: 'Początkujący poszukiwacz przygód. Wybierz klasę na poziomie 20.',
        color: '#95a5a6',
        baseStats: { hp: 120, mp: 40, damage: 5, armor: 2, accuracy: 10, dodge: 3 },
        baseAttributes: { str: 2, dex: 2, agi: 2, vit: 2, int: 0 },
        hpPerLevel: 8, mpPerLevel: 4,
        attacksPerTurn: 1,
        baseAttackSpeed: 1.4,
        allowedItems: ['sword','dagger','club','tunic','simple_pants','sandals','wooden_shield'],
        skills: [
            { level: 1, id: 'basic_strike', name: 'Prosty Cios', desc: '1.5x obrażenia (+0.2x/lv)', cost: 6, type: 'melee', baseMult: 1.5, multPerLv: 0.2 },
            { level: 3, id: 'bandage', name: 'Opatrunek', desc: 'Leczy 15% HP (+3%/lv)', cost: 10, type: 'buff' },
            { level: 6, id: 'battle_shout', name: 'Okrzyk Bitewny', desc: '+20% DMG na 5s (+1s/lv)', cost: 12, type: 'buff' },
            { level: 10, id: 'desperate_blow', name: 'Desperacki Cios', desc: '2x DMG (+0.3x/lv)', cost: 15, type: 'melee', baseMult: 2.0, multPerLv: 0.3 },
            { level: 15, id: 'survivor', name: 'Instynkt Przetrwania', desc: '+25% HP na 5s (+1s/lv)', cost: 14, type: 'buff' },
        ],
        tree: {
            combat: { name: 'Walka', nodes: [
                { id: 'n_str', name: 'Siła', desc: '+2 Obrażenia', stat: 'damage', val: 2 },
                { id: 'n_tough', name: 'Twardość', desc: '+10 HP', stat: 'maxHp', val: 10 },
                { id: 'n_power', name: 'Moc', desc: '+3 Obrażenia', stat: 'damage', val: 3 },
                { id: 'n_endure', name: 'Wytrzymałość', desc: '+15 HP', stat: 'maxHp', val: 15 },
                { id: 'n_might', name: 'Potęga', desc: '+5 Obrażenia', stat: 'damage', val: 5 },
            ]},
            survival: { name: 'Przetrwanie', nodes: [
                { id: 'n_dodge', name: 'Unik', desc: '+2 Unik', stat: 'dodge', val: 2 },
                { id: 'n_armor', name: 'Pancerz', desc: '+2 Pancerz', stat: 'armor', val: 2 },
                { id: 'n_nimble', name: 'Zwinność', desc: '+3 Unik', stat: 'dodge', val: 3 },
                { id: 'n_shield', name: 'Ochrona', desc: '+3 Pancerz', stat: 'armor', val: 3 },
                { id: 'n_iron', name: 'Żelazo', desc: '+5 Pancerz', stat: 'armor', val: 5 },
            ]},
        },
    },
};
